use customer_shopping_behaviour;
-- QI. What is the total revenue generated by male vs. female customers?
select gender, Sum(purchase_amount) as revenue from customer	
group by gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount.
select customer_id, purchase_amount from customer 
where discount_applied = 'Yes' and purchase_amount >= (Select avg(purchase_amount) from customer);


-- What are the top5 products with highest average review rating ?
select item_purchased, ROUND(avg(review_rating),2) as 'Average Product Rating'
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,ROUND(avg(purchase_amount),2) from customer
where shipping_type in ('Standard','Express')
group by shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers.
SELECT subscription_status, 
       SUM(purchase_amount) AS total_purchase,
       round(AVG(purchase_amount),2) AS avg_purchase,
       COUNT(*) AS total_customers
FROM customer
GROUP BY subscription_status;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/ count(*),2) as discount
from customer
group by item_purchased
order by discount desc
limit 5;